steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: python -m pip install --upgrade pip
    displayName: Upgrade Pip
  - script: |
      python --version
      pip --version
    displayName: Check Python version
  - script: pip install -r requirements.txt
    displayName: Pip Install
  - script: pip install wheel
    displayName: Install Wheel
  - script: |
      mypy mathtools --strict
      mypy tests --ignore-missing-imports --strict
    displayName: mypy
  - script: pytest --doctest-modules
    displayName: pytest
  - script: python setup.py bdist_wheel
    displayName: Build wheel
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: 'dist'
      artifactName: 'artifact'
      artifactType: 'container'
