steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: python -m pip install --upgrade pip
    displayName: Upgrade Pip
  - script: python --version
    displayName: Check Python version
  - script: pip --version
    displayName: Check Pip version
  - script: pip install -r requirements.txt
    displayName: Pip install dependencies
  - script: pip install wheel
    displayName: Install wheel
  - script: mypy mathtools --strict
    displayName: mypy source code
  - script: mypy tests --ignore-missing-imports --strict
    displayName: mypy test code
  - script: pytest --doctest-modules
    displayName: pytest
  - script: python setup.py bdist_wheel
    displayName: Build wheel
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: 'dist'
      artifactName: 'artifact'
      artifactType: 'container'
