phases:
- phase: 'Phase_1'
  displayName: 'Build and Test'
  queue:
    matrix:
      Python36:
        python.version: '3.6'
      Python37-dev:
        python.version: '>= 3.7.0a'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      addToPath: 'true'
  - script: make dependencies
    displayName: 'Install dependencies'
  - script: make tests
    displayName: 'Test'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'

- phase: 'Phase_2'
  displayName: 'Publish'
  dependsOn: 'Phase_1'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
      addToPath: 'true'
  - script: python setup.py sdist
    displayName: Build sdist
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: 'dist'
      artifactName: 'dist'
      artifactType: 'container'
