# Python package
# Build and test a Python package on multiple Python versions. Upload to a Python package index.
# https://aka.ms/yaml

phases:
- phase: 'Phase_1'
  displayName: 'Build and Test'
  queue:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'
      Python37-dev:
        PYTHON_VERSION: '>= 3.7.0a'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
      addToPath: 'true'
  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install Dependencies'
  # - script: 'pip install flake8 && flake8'
  #   displayName: 'Flake8'
  - script: pip install pytest && pytest tests --doctest-modules
    displayName: 'pytest'

- phase: 'Phase_2'
  displayName: 'Publish'
  dependsOn: 'Phase_1'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: 'true'
  - script: python -m pip install --upgrade pip && pip install wheel && python setup.py bdist_wheel
    displayName: Build Wheel
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: 'dist'
      artifactName: 'artifact'
      artifactType: 'container'
  # - task: PyPIPublisher@0
  #   inputs:
  #     wd: '$(Build.SourcesDirectory)'
