variables:
  build.artifactStagingDirectory: 'dist'
steps:
  - script: pip install -r requirements.txt
  - script: |
      mypy mathtools --strict
      mypy tests --ignore-missing-imports --strict
  - script: pytest --doctest-modules
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'