name: CI

on:
- push
- workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: make dependencies
    - run: make typecheck
    - run: make tests
