name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make dependencies

    - name: Run tests
      run: make tests
